name: Mod Validation

on:
  push:
    branches:
      - 'vcmi-*'
  pull_request:
  workflow_dispatch:


jobs:
  validate-json:
    if: always()
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      PRE_COMMIT_FILE: pre-commit.stdouterr
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11' 
        - name: Cache pre-commit hooks
          uses: actions/cache@v4
          with:
            path: ~/.cache/pre-commit
            key: ${{ runner.os }}-pre-commit-hooks-${{ hashFiles('.pre-commit-config.yaml') }}
    
        - name: Setup pre-commit
          run: pip3 install pre-commit
        - name: Run pre-commit
          id: pre-commit
          continue-on-error: true
          run: |
            # NOTE: Bash extending globing is used to exclude stdouterr files from pre-commit run
            shopt -s extglob
            pre-commit run \
              --color never \
              --all-files |&
              tee "${PRE_COMMIT_FILE}"
            shopt -u extglob
        - name: Post scans as PR comment
          uses: actions/github-script@v7
          if: always()
          continue-on-error: true
          with:
            script: |
              const fs = require('fs');
              const preCommitFile = process.env.PRE_COMMIT_FILE;

              let preCommitOutput = '';
              try {
              preCommitOutput = fs.readFileSync(preCommitFile, 'utf8');
              } catch (e) {
              preCommitOutput = ':warning: No pre-commit output found.';
              }

              const githubWorkflowRunUrl = process.env.GITHUB_WORKFLOW_RUN_URL;
              const githubRunNumber = process.env.GITHUB_RUN_NUMBER;
              const githubRunAttempt = process.env.GITHUB_RUN_ATTEMPT;

              const commentHeader = '### :white_check_mark: Pre-commit Validation Output :white_check_mark:\n\n';
              const commentBody = `${commentHeader}\`\`\`\n${preCommitOutput}\n\`\`\`\n\n[View Workflow Run #${githubRunNumber} (Attempt ${githubRunAttempt})](${githubWorkflowRunUrl})`;

              const { data: comments } = await github.rest.issues.listComments({
              ...context.repo,
              issue_number: context.issue.number
              });
              const existingComment = comments.find(comment => 
              comment.user.login === 'github-actions[bot]' && 
              comment.body.startsWith(commentHeader)
              );
              if (existingComment) {
              await github.rest.issues.updateComment({
                ...context.repo,
                comment_id: existingComment.id,
                body: commentBody
              });
              } else {
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: context.issue.number,
                body: commentBody
              });
              }
        - name: Post as GHA summary
          uses: actions/github-script@v7
          if: always()
          continue-on-error: true
          with:
            script: |
              const fs = require('fs');
              const preCommitFile = process.env.PRE_COMMIT_FILE;

              let summaryOutput = '';
              try {
                summaryOutput = fs.readFileSync(preCommitFile, 'utf8');
              } catch (e) {
                summaryOutput = ':warning: No summary output found.';
              }

              const githubWorkflowRunUrl = process.env.GITHUB_WORKFLOW_RUN_URL;
              const githubRunNumber = process.env.GITHUB_RUN_NUMBER;
              const githubRunAttempt = process.env.GITHUB_RUN_ATTEMPT;

              const summaryHeader = '### :memo: Summary Output :memo:\n\n';
              const summaryBody = `${summaryHeader}\`\`\`\n${summaryOutput}\n\`\`\`\n\n[View Workflow Run #${githubRunNumber} (Attempt ${githubRunAttempt})](${githubWorkflowRunUrl})`;

              await github.summary.addRaw(summaryBody);
              await github.summary.write();
